server:
  port: 8080

spring:
  application:
    name: gateway-proxy

zuul:
  ignoredServices: '*'
  routes:
    employee-service:
      prefix: /api
      path: /employees/**
      stripPrefix: false
    department-service:
      prefix: /api
      path: /departments/**
      stripPrefix: false
    organization-service:
      prefix: /api
      path: /organization/**
      stripPrefix: false

management:
  endpoints:
    web:
      exposure:
        include:
          - '*'

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka