server:
  port: 8083

spring:
  application:
    name: organization-service
  sleuth:
    sampler:
      probability: 1.0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka